# Data Science configs
test_size: 0.2
random_state: 3

# Parameterize target/features
features:
  - engines
  - passenger_capacity
  - crew
  - d_check_complete
  - moon_clearance_complete
target: price

# App prefrences
host: "127.0.0.1"
port: 5000
